=== camilo86/DataConnectorSchema/schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "properties": {
        "id": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "apiVersion": {
            "enum": [
                "2022-09-01-preview"
            ]
        },
        "type": {
            "enum": [
                "Microsoft.SecurityInsights/dataConnectorDefinitions"
            ]
        },
        "location": {
            "enum": [
                "{{location}}"
            ]
        },
        "kind": {
            "enum": [
                "Customizable"
            ]
        },
        "properties": {
            "properties": {
                "connectorUiConfig": {
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "title": {
                            "type": "string"
                        },
                        "publisher": {
                            "type": "string"
                        },
                        "descriptionMarkdown": {
                            "type": "string"
                        },
                        "graphQueriesTableName": {
                            "type": "string"
                        },
                        "graphQueries": {
                            "type": "array",
                            "items": {
                                "properties": {
                                    "metricName": {
                                        "type": "string"
                                    },
                                    "legend": {
                                        "type": "string"
                                    },
                                    "baseQuery": {
                                        "type": "string"
                                    }
                                }
                            }
                        },
                        "sampleQueries": {
                            "type": "array",
                            "items": {
                                "properties": {
                                    "query": {
                                        "type": "string"
                                    },
                                    "description": {
                                        "type": "string"
                                    }
                                }
                            }
                        },
                        "dataTypes": {
                            "type": "array",
                            "items": {
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "lastDataReceivedQuery": {
                                        "type": "string"
                                    }
                                }
                            }
                        },
                        "connectivityCriteria": {
                            "type": "array",
                            "items": {
                                "properties": {
                                    "type": {
                                        "enum": [
                                            "HasDataConnectors"
                                        ]
                                    }
                                }
                            }
                        },
                        "permissions": {
                            "properties": {
                                "resourceProvider": {
                                    "type": "array",
                                    "items": {
                                        "properties": {
                                            "provider": {
                                                "type": "string"
                                            },
                                            "permissionsDisplayText": {
                                                "type": "string"
                                            },
                                            "providerDisplayName": {
                                                "type": "string"
                                            },
                                            "scope": {
                                                "type": "string"
                                            },
                                            "requiredPermissions": {
                                                "properties": {
                                                    "write": {
                                                        "type": "boolean"
                                                    },
                                                    "read": {
                                                        "type": "boolean"
                                                    },
                                                    "delete": {
                                                        "type": "boolean"
                                                    }
                                                }
                                            }
                                        }
                                    }
                                },
                                "customs": {
                                    "type": "array",
                                    "items": {
                                        "properties": {
                                            "name": {
                                                "type": "string"
                                            },
                                            "description": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "instructions": {
                            "type": "array",
                            "items": {
                                "$ref": "#/$defs/instructionStep"
                            }
                        }
                    }
                }
            }
        }
    },
    "$defs": {
        "instructionStep": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": [
                        "Label",
                        "Textbox",
                        "OAuthForm"
                    ]
                },
                "title": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "parameters": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "instructions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/$defs/instructionStep"
                    }
                }
            }
        }
    }
}

=== camilo86/DataConnectorSchema/Custom.DataConnectorDefinition.json
{
    "id": "CustomDataConnector",
    "name": "CustomDataConnector",
    "apiVersion": "2022-09-01-preview",
    "type": "Microsoft.SecurityInsights/dataConnectorDefinitions",
    "kind": "Customizable",
    "location": "{{location}}",
    "properties": {
        "connectorUiConfig": {
            "id": "CustomDataConnector",
            "title": "Custom Data Connector",
            "publisher": "Microsoft",
            "descriptionMarkdown": "# **New** Custom Data Connector",
            "graphQueriesTableName": "CustomDataTable",
            "graphQueries": [
                {
                    "metricName": "Events recieved",
                    "legend": "Custom data events recieved",
                    "baseQuery": "CustomDataTable | top 10"
                }
            ],
            "dataTypes": [
                {
                    "name": "CustomDataType",
                    "lastDataReceivedQuery": "CustomDataTable | summarize by count()"
                }
            ],
            "sampleQueries": [
                {
                    "query": "CustomDataTable | sort by TimeGenerated desc"
                }
            ],
            "connectivityCriteria": [
                {
                    "type": "HasDataConnectors"
                }
            ],
            "permissions": {
                "resourceProvider": [
                    {
                        "provider": "Microsoft.OperationalInsights/workspaces",
                        "permissionsDisplayText": "Read and Write permissions are required.",
                        "providerDisplayName": "Workspace",
                        "scope": "Workspace",
                        "requiredPermissions": {
                            "write": true,
                            "read": true,
                            "delete": true
                        }
                    }
                ],
                "customs": [
                    {
                        "name": "Custom Data Provider credentials",
                        "description": "API Key for Custom Data Provider required"
                    }
                ]
            },
            "instructions": [
                {
                    "title": "Connect CustomDataProvider to start collecting event logs to Sentinel",
                    "description": "Provide the required values below",
                    "instructions": [
                        {
                            "type": "Textbox",
                            "parameters": {
                                "label": "API Key",
                                "type": "text",
                                "name": "apiKey"
                            }
                        },
                        {
                            "type": "OAuthForm",
                            "parameters": {
                                "clientIdLabel": "Client ID",
                                "clientSecretLabel": "Client Secret",
                                "connectButtonLabel": "Connect",
                                "disconnectButtonLabel": "Disconnect"
                            }
                        }
                    ]
                }
            ]
        }
    }
}
